export type {
  BearerTokenResolver,
  CustomTenantExtractor,
  MultiTenantModuleAsyncOptions,
  MultiTenantModuleOptions,
  OnTenantIdExtracted,
  OnTenantMissing,
  OnTenantNotFound,
  OnTenantResolved,
  Tenant,
  TenantCacheOptions,
  TenantEventContext,
  TenantEventHooks,
  TenantExtractionStrategy,
  TenantResolver,
} from './tenant.interface';
