export type {
  BearerTokenResolver,
  CustomTenantExtractor,
  MultiTenantModuleAsyncOptions,
  MultiTenantModuleOptions,
  OnTenantIdExtracted,
  OnTenantMissing,
  OnTenantNotFound,
  OnTenantResolved,
  OnTenantValidationFailed,
  Tenant,
  TenantCacheOptions,
  TenantEventContext,
  TenantEventHooks,
  TenantExtractionStrategy,
  TenantResolver,
  TenantValidationResult,
  TenantValidator,
} from './tenant.interface';
